#!/bin/sh

## Simple monitoring script for cron
##
## Copyright (C) 2015  Lukas Matt <lukas@zauberstuhl.de>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

help() {
  echo "Usage:\n\t$0 <command-to-be-executed>\n"
  exit 1;
}

COMMAND=$@
COMMANDNAME=`echo $COMMAND |cut -d' ' -f1 |sed 's/\/\(\[\w\d\]+\)$/\1/'`

if [ "$COMMAND" = "" ]; then help; fi

PID=`ps w |grep -i $COMMANDNAME |grep -v grep |grep -v $0 |sed 's/^\s*//' |cut -d' ' -f1`

if [ "$PID" = "" ]; then
  echo "[$COMMANDNAME] Job is not running! Restarting.."
  $COMMAND
else
  echo "[$COMMANDNAME] Job is running!"
fi
