#!/bin/sh /etc/rc.common

## passwd wrapper for VPN password changes
##
## Copyright (C) 2015  Lukas Matt <lukas@zauberstuhl.de>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

START=99

. /etc/profile

install() {
  local OVPNPATH=/tmp/openvpn
  local OSSLPATH=/tmp/libopenssl
  [ ! -d ${OVPNPATH} ] && mkdir ${OVPNPATH}
  [ ! -d ${OSSLPATH} ] && mkdir ${OSSLPATH}
  command opkg update || exit 1
  # install openvpn
  cd ${OVPNPATH}
  tar xzf $(opkg download openvpn-openssl | grep Downloaded | cut -d\  -f4 | sed '$s/.$//')
  tar xzf data.tar.gz
  rm -f pkg.tar.gz data.tar.gz control.tar.gz debian-binary getopenvpn.sh
  # install libopenssl
  cd ${OSSLPATH}
  tar xzf $(opkg download libopenssl | grep Downloaded | cut -d\  -f4 | sed '$s/.$//')
  tar xzf data.tar.gz
  rm -f control.tar.gz debian-binary data.tar.gz
}

start () {
  # lvl 99 is not enough the script is too
  sleep 10 # fast for the install step
  install # setup openvpn and libssl
  command openvpn --writepid /tmp/openvpn/ovpn.pid --daemon --config /etc/openvpn/client.conf
}

stop() {
  PIDOF=$(ps | egrep openvpn | egrep  -v grep | awk '{print $1}')
  kill ${PIDOF}
}
