#!/bin/sh /etc/rc.common

## passwd wrapper for VPN password changes
##
## Copyright (C) 2015  Lukas Matt <lukas@zauberstuhl.de>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

START=99

. /etc/profile

install() {
  local TMP=/tmp
  local OVPNPATH=$TMP/openvpn
  local OSSLPATH=$TMP/libopenssl
  local URL=http://www2.hs-esslingen.de/~lumait03/openWRT
  [ ! -d ${OVPNPATH} ] && mkdir ${OVPNPATH}
  [ ! -d ${OSSLPATH} ] && mkdir ${OSSLPATH}
  # TODO NOT TESTED
  # install liblzo and kmod
  cd ${TMP} \
    && wget $URL/liblzo_2.08-1_ar71xx.ipk \
    && wget $URL/kmod-tun_3.18.20-1_ar71xx.ipk

  opkg install liblzo_2.08-1_ar71xx.ipk \
    && opkg install kmod-tun_3.18.20-1_ar71xx.ipk

  # install openvpn
  cd ${OVPNPATH} \
    && wget $URL/openvpn-openssl_2.3.6-2_ar71xx.ipk
  tar xzf openvpn-openssl_2.3.6-2_ar71xx.ipk; tar xzf data.tar.gz
  # cleanup
  rm -f pkg.tar.gz data.tar.gz control.tar.gz debian-binary getopenvpn.sh

  # install libopenssl
  cd ${OSSLPATH} \
    && wget $URL/libopenssl_1.0.2c-0_ar71xx.ipk
  tar xzf libopenssl_1.0.2c-0_ar71xx.ipk; tar xzf data.tar.gz
  # cleanup
  rm -f control.tar.gz debian-binary data.tar.gz
}

start () {
  # lvl 99 is not enough the script is too
  sleep 10 # fast for the install step
  install # setup openvpn and libssl
  command openvpn --writepid /tmp/openvpn/ovpn.pid --daemon --config /etc/openvpn/client.conf
}

stop() {
  PIDOF=$(ps | egrep openvpn | egrep  -v grep | awk '{print $1}')
  kill ${PIDOF}
}
