#!/bin/sh

## passwd wrapper for VPN password changes
##
## Copyright (C) 2015  Lukas Matt <lukas@zauberstuhl.de>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

USER=$1

if [ "$USER" != "root" ]
then
  ../../bin/busybox passwd $@
  exit 0;
fi

read pass
read retype

echo -e "user1\n$pass" > /etc/openvpn/pass.txt
echo -e "$pass\n$retype" | ../../bin/busybox passwd root
